### ISSUE TITLE
Curious error being raised when caching 

### ISSUE THREAD

**Issue by arm61** [showyourwork/showyourwork#120]
Not really sure what this error is telling me but (I think) it is making the workflow stop

```
Traceback (most recent call last):
  File "/Users/andrewmccluskey/.showyourwork/env/lib/python3.9/site-packages/showyourwork/patches.py", line 138, in fetch
    raise exceptions.FileNotFoundOnZenodo(None)
showyourwork.exceptions.zenodo.FileNotFoundOnZenodo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrewmccluskey/.showyourwork/env/lib/python3.9/site-packages/showyourwork/patches.py", line 147, in fetch
    sandbox.download_file(
  File "/Users/andrewmccluskey/.showyourwork/env/lib/python3.9/site-packages/showyourwork/zenodo.py", line 644, in download_file
    raise exceptions.FileNotFoundOnZenodo(file.name)
showyourwork.exceptions.zenodo.FileNotFoundOnZenodo

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrewmccluskey/.showyourwork/env/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 599, in _callback
    raise ex
  File "/Users/andrewmccluskey/.showyourwork/env/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/andrewmccluskey/.showyourwork/env/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 581, in cached_or_run
    self.workflow.output_file_cache.fetch(job)
  File "/Users/andrewmccluskey/.showyourwork/env/lib/python3.9/site-packages/showyourwork/patches.py", line 156, in fetch
    exceptions.restore_trace()
  File "/Users/andrewmccluskey/.showyourwork/env/lib/python3.9/site-packages/showyourwork/exceptions/base.py", line 54, in restore_trace
    flag.unlink()
  File "/Users/andrewmccluskey/.showyourwork/env/lib/python3.9/pathlib.py", line 1354, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/andrewmccluskey/work/research/msd-errors/.showyourwork/flags/DISABLE_SNAKEMAKE_EXCEPTIONS'
```

**Comment by arm61** [comment]
It *appears* to happen randomly (as far as I can tell), but might be more common when more cores are used. I am seeing it happen more with `--cores 6` versus `--cores 4`. Dunno if that is helpful

**Comment by rodluger** [comment]
Zenodo Sandbox has been experiencing issues the last few days -- this could be related, especially since you say it seems to be happening randomly. In any event, cache issues should always be non-fatal in `showyourwork`, and yours was breaking your workflow. I patched the error that was causing it, so please try out the version on main (`a2db7450e0013bd2641f46df24d5470bc8b95d6d`) to see if it helps. I'll release `v0.3.1` in the next week-ish, so at that point you can just upgrade.

**Comment by arm61** [comment]
Cool I am running on the the latest now and `--cores 6` doesn't seem to be throwing anymore errors. I'll close this. Thanks again!
