### ISSUE TITLE
AttributeError: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by rodluger** [showyourwork/showyourwork#215]
Many workflows may start failing soon with the following [error](https://github.com/showyourwork/test-default/actions/runs/3206142982/jobs/5239520715):

```
Traceback (most recent call last):
  File "/home/runner/.showyourwork/conda/d9b5401cad5d7920c0bc8d4a79457fac/lib/python3.9/site-packages/snakemake/__init__.py", line 701, in snakemake
    success = workflow.execute(
  File "/home/runner/.showyourwork/conda/d9b5401cad5d7920c0bc8d4a79457fac/lib/python3.9/site-packages/snakemake/workflow.py", line 1060, in execute
    logger.run_info("/n".join(dag.stats()))
  File "/home/runner/.showyourwork/conda/d9b5401cad5d7920c0bc8d4a79457fac/lib/python3.9/site-packages/snakemake/dag.py", line 2191, in stats
    yield tabulate(rows, headers="keys")
  File "/home/runner/.showyourwork/conda/d9b5401cad5d7920c0bc8d4a79457fac/lib/python3.9/site-packages/tabulate/__init__.py", line 2048, in tabulate
    list_of_lists, headers = _normalize_tabular_data(
  File "/home/runner/.showyourwork/conda/d9b5401cad5d7920c0bc8d4a79457fac/lib/python3.9/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/runner/.showyourwork/conda/d9b5401cad5d7920c0bc8d4a79457fac/lib/python3.9/site-packages/tabulate/__init__.py", line 1471, in <lambda>
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/runner/.showyourwork/conda/d9b5401cad5d7920c0bc8d4a79457fac/lib/python3.9/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
    (len(row) >= 1 and row[0] == SEPARATING_LINE)
  File "/home/runner/.showyourwork/conda/d9b5401cad5d7920c0bc8d4a79457fac/lib/python3.9/site-packages/snakemake/rules.py", line 1138, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'
```

(see discussion in #214). This is a `Snakemake` issue triggered by the latest release of `tabulate` (`0.9.0`). Since the `tabulate` dependency is not pinned in the `Snakemake` install, it defaults to the latest version, so any workflow in which `Snakemake` is installed anew (say, a new repo or a new, non-cached run on GitHub Actions) should run into this.

I'm looking into ways to fix this -- it's not easy! Please stand by...

**Comment by rodluger** [comment]
I released a [postfix for `v0.3.1` on PyPI](https://pypi.org/project/showyourwork/0.3.1.post1/) that pins `tabulate==0.8.10` and this fixes the issue for fresh runs on CI (e.g., [here](https://github.com/showyourwork/test-default/actions/runs/3206246078/jobs/5239761328)). Will release a postfix for `0.3.0` momentarily.

Locally, users should upgrade `showyourwork` by running `pip install -U showyourwork`. Consider also bumping the version of `showyourwork` in your workflow from `0.3.1` to `0.3.1.post1`.

If anyone is still running into issues because of this, please let me know!
