### ISSUE TITLE
`AttributeError` when running `showyourwork clean --deep`

### ISSUE THREAD

**Issue by wtbarnes** [showyourwork/showyourwork#353]
When doing a "deep clean" of the environment, with `showyourwork clean --deep`, I get the following exception,

```python traceback
Building DAG of jobs...
Traceback (most recent call last):
  File "/Users/wtbarnes/mambaforge/bin/showyourwork", line 8, in <module>
    sys.exit(entry_point())
  File "/Users/wtbarnes/mambaforge/lib/python3.9/site-packages/showyourwork/cli/__init__.py", line 59, in entry_point
    main()
  File "/Users/wtbarnes/mambaforge/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/wtbarnes/mambaforge/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/wtbarnes/mambaforge/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/wtbarnes/mambaforge/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/wtbarnes/mambaforge/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/wtbarnes/mambaforge/lib/python3.9/site-packages/showyourwork/cli/main.py", line 300, in clean
    commands.clean(
  File "/Users/wtbarnes/mambaforge/lib/python3.9/site-packages/showyourwork/cli/commands/clean.py", line 42, in clean
    if paths.user().home_temp.exists():
AttributeError: 'user' object has no attribute 'home_temp'
```

As far as I can tell, there is no `home_temp` attribute exposed on `paths.user()`: https://github.com/showyourwork/showyourwork/blob/8038af82f9bfcb42d451760b3cf49585b9a3d3ad/showyourwork/paths.py#L54-L77. Is this meant to be just `temp`?

**Comment by dfm** [comment]
Thanks for the report! It looks like `temp` is cleaned up [above](https://github.com/showyourwork/showyourwork/blob/8038af82f9bfcb42d451760b3cf49585b9a3d3ad/showyourwork/cli/commands/clean.py#LL30C1-L31C41), so I expect this should just be removed. Would you be willing to open a PR?

**Comment by wtbarnes** [comment]
Sure! Is this just a matter of removing the last conditional inside of the `if deep` conditional?

**Comment by dfm** [comment]
Great! Yeah - that seems like it should do the trick. Thanks!
