### ISSUE TITLE
Steps 1 and 2 in QuickStart failed... argh.

### ISSUE THREAD

**Issue by GeoffreyCompere** [showyourwork/showyourwork#375]
Encouraged with the features I gave it a try starting with the Tutorial QuickStart. But..
1. At install (pip install -U showyourwork) on a MacOS 12.6 , I got the error:
ERROR: cookiecutter 2.1.1 has requirement requests>=2.23.0, but you'll have requests 2.22.0 which is incompatible.

2. And then on line 2 of the QuickStart tutorial, I tried showyourwork setup myname/myrepository and I got the error: 
Traceback (most recent call last):
  File "/opt/miniconda3/bin/showyourwork", line 5, in <module>
    from showyourwork.cli import entry_point
  File "/opt/miniconda3/lib/python3.7/site-packages/showyourwork/cli/__init__.py", line 13, in <module>
    from .main import entry_point
  File "/opt/miniconda3/lib/python3.7/site-packages/showyourwork/cli/main.py", line 9, in <module>
    from . import commands
  File "/opt/miniconda3/lib/python3.7/site-packages/showyourwork/cli/commands/__init__.py", line 9, in <module>
    from .setup import setup
  File "/opt/miniconda3/lib/python3.7/site-packages/showyourwork/cli/commands/setup.py", line 12, in <module>
    from ...zenodo import Zenodo
  File "/opt/miniconda3/lib/python3.7/site-packages/showyourwork/zenodo.py", line 15, in <module>
    from .config import get_run_type
  File "/opt/miniconda3/lib/python3.7/site-packages/showyourwork/config.py", line 142
    if deps := dependencies.get(file, []):
             ^
SyntaxError: invalid syntax

Am I missing something important? If I receive no solution, my experience with Showyourwork will stop here I'm afraid.

**Comment by dfm** [comment]
It looks like you're using Python 3.7 which isn't supported by showyourwork ([we need at least v3.8!](https://github.com/showyourwork/showyourwork/blob/a4ae959a7561c093cf177b38d1d8f72512f0cf74/setup.py#L20)) so you'll need to update your Python installation. In particular, I'd recommend creating a fresh conda environment with Python 3.9 (which is the main version we test).

**Comment by dfm** [comment]
Closing due to inactivity.
