### ISSUE TITLE
OrcID causes an error in compile?

### ISSUE THREAD

**Issue by jwreep** [showyourwork/showyourwork#454]
I'm trying to build an article with this package, and I'm having trouble with OrcID.  My article builds and runs correctly when I don't include OrcID, but crashes when I do.

That is, in `ms.tex` if I replace this line
`\author{Jeffrey W. Reep}`
with 
`\author[0000-0003-4739-1152]{Jeffrey W. Reep}`

it then throws an error:
```
Preprocess: Setting up the workflow...
Traceback (most recent call last):
  File "/Users/reep/Documents/Forks/ebtel_abundances/.snakemake/scripts/tmpt4kss5v3.preprocess.py", line 484, in <module>
    config["tree"] = get_json_tree(snakemake.input[0])
  File "/Users/reep/Documents/Forks/ebtel_abundances/.snakemake/scripts/tmpt4kss5v3.preprocess.py", line 409, in get_json_tree
    free_floating_graphics = [
  File "/Users/reep/Documents/Forks/ebtel_abundances/.snakemake/scripts/tmpt4kss5v3.preprocess.py", line 412, in <listcomp>
    if graphic not in config["tex_files_out"]
KeyError: 'tex_files_out'
```

It seems #400 had a similar problem.  Based on that, I tried to add edit the `environment.yml` file to use showyourwork v.0.4.2, but that didn't solve the issue.

Any help would be greatly appreciated!

**Comment by jwreep** [comment]
The fix [suggested in this comment](https://github.com/showyourwork/showyourwork/issues/400#issuecomment-1729999403) did solve the issue for me as well.

**Comment by HealthyPear** [comment]
@dfm Until the proper solution will be figured out I think for the time being this issue should be added to the FAQ with a link to that comment. I can open a PR if you wish.
