### ISSUE TITLE
syw preprocessing fails when `\author` is passed an orchid ID

### ISSUE THREAD

**Issue by tedjohnson12** [showyourwork/showyourwork#464]
showyourwork version: 0.4.4.dev37+g1526059 (latest on main branch as of August 1)
snakemake version:  7.15.2
Python version: 3.9.19
Minimal reproducible example: 

In one of my projects I changed the author line in `ms.tex`
`\author{Author Name}`
to
`\author[0000-0000-0000-0000]{Author Name}`
in order to link my Orchid ID (of course, I used my actual name and ID). My project, which had successfully built previously, now gives me the following error message upon `showyourwork build`:
```
Preprocess: Setting up the workflow...
Traceback (most recent call last):
  File "/home/ted/github/vspec-paper/.snakemake/scripts/tmp0jonyj1k.preprocess.py", line 484, in <module>
    config["tree"] = get_json_tree(snakemake.input[0])
  File "/home/ted/github/vspec-paper/.snakemake/scripts/tmp0jonyj1k.preprocess.py", line 409, in get_json_tree
    free_floating_graphics = [
  File "/home/ted/github/vspec-paper/.snakemake/scripts/tmp0jonyj1k.preprocess.py", line 412, in <listcomp>
    if graphic not in config["tex_files_out"]
KeyError: 'tex_files_out'
Error in rule syw__preprocess:
    jobid: 1
    output: .showyourwork/config.json

RuleException:
CalledProcessErrorin line 98 of /home/ted/anaconda3/envs/syw/lib/python3.9/site-packages/showyourwork/workflow/rules/preprocess.smk:
Command 'set -euo pipefail;  /home/ted/anaconda3/envs/syw/bin/python /home/ted/github/vspec-paper/.snakemake/scripts/tmp0jonyj1k.preprocess.py' returned non-zero exit status 1.
  File "/home/ted/anaconda3/envs/syw/lib/python3.9/site-packages/showyourwork/workflow/rules/preprocess.smk", line 98, in __rule_4
  File "/home/ted/anaconda3/envs/syw/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Exiting because a job execution failed. Look above for error message
```

I can't find anything in the syw docs about orchid, but I've seen examples of other projects that include IDs, so I am not sure why I am having this problem.

**Comment by tedjohnson12** [comment]
Github won't allow me to upload the example, but here is what I did to reproduce the problem:
* `$ showyourwork setup example/example`
* Replace authors in `ms.text` with: 
    ```% Author list
    % \author[0000-0000-0000-0000]{My Name} % doesn't work
    \author{My Name} % works
    \affiliation{My University}
    ```
* Run `showyourwork build` once with each author line commented.

**Comment by HealthyPear** [comment]
This issue is the same as in #454, where it is suggested to try the fix proposed by [this comment](https://github.com/showyourwork/showyourwork/issues/400#issuecomment-1729999403).

Can you try to see if this fixes your problem?

If yes, I'll open a PR to put this in the documentation FAQ until we find a better solution.

**Comment by tedjohnson12** [comment]
Thank you! Yes, this works, however note that in order to build the article using GH actions I have to point the `showyourwork-spec` parameter to my own fork.

As far as long-term fixes, the string `"tex_files_out"` does not appear anywhere else in the repository so I am not sure what it is specifically referring to. If it is a key that is occasionally in `snakemake.config` depending on the project, then perhaps a solution like
```
if "tex_files_out" in config:
    free_floating_graphics = [
        graphic
        for graphic in free_floating_graphics
        if graphic not in config["tex_files_out"]
    ]
```
would work best.

Otherwise, what do you think of an improved error message? This error will arise for any image not wrapped in `<FIGURE>` tags in showyourwork.xml, so maybe in the case of a KeyError we point the user to both the FAQ and note that it could be caused by using `\includegraphics` outside of a figure environment?

**Comment by thomasckng** [comment]
> This issue is the same as in #454, where it is suggested to try the fix proposed by [this comment](https://github.com/showyourwork/showyourwork/issues/400#issuecomment-1729999403).
> 
> Can you try to see if this fixes your problem?
> 
> If yes, I'll open a PR to put this in the documentation FAQ until we find a better solution.

Got the same problem and fixed by the solution here temporarily.

**Comment by HealthyPear** [comment]
@dfm I wanted to tackle this issue next

as @tedjohnson12 mentiones above, this key is nowhere to be found in the current development version

I am not in this project long enough to remember, so I did what anybody would do: (git) blame the devs 😄 

It seems that the related change has been [committed](https://github.com/showyourwork/showyourwork/commit/cc8c7568a24cdc65e6d0fa2f6110b3cf7460d76b) by @rodluger on Mar 24, 2022 associated to [this](https://github.com/showyourwork/showyourwork/pull/92) jumbo PR

Even in the whole code associated to this point of history that string is used only there: is it something related to snakemake only?

I would go for @tedjohnson12 solution: it will fix this issue, and still do what is in the code if it happens that the key actually appears, but I would rather much prefer actually understanding why we are looking for it given that `tex_files_in` seems instead quite critical.

I will open a draft PR with this temporary fix and a new test in the meanwhile...
